[package]
name = "celestia-relayer"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "node-bindings"] }
alloy-network.workspace = true
alloy-signer-local.workspace = true
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
ibc-eureka-relayer-lib.workspace = true
ibc-eureka-solidity-types.workspace = true
prost.workspace = true
prover-client.workspace = true
serde.workspace = true
serde_json.workspace = true
tendermint-rpc.workspace = true
tendermint.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-reflection = "0.12.0"
tracing-subscriber.workspace = true
tracing.workspace = true

[build-dependencies]
tonic-build = { workspace = true, default-features = true }
